# Generated by Django 3.2.5 on 2021-08-18 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210818_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='network_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
