# Generated by Django 3.2.5 on 2021-08-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_post_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
    ]
